Update action.yml

diff --git a/eng/common/actions/backport/action.yml b/eng/common/actions/backport/action.yml
--- a/eng/common/actions/backport/action.yml
+++ b/eng/common/actions/backport/action.yml
@@ -28,6 +28,8 @@ runs:
     - shell: bash
       id: pushbackport
       run: |
+        trap 'echo "::set-output name=error_occurred::1"' err
+
         git checkout ${{ steps.targetbranch.outputs.branchname }}
         git clean -xdff
   
@@ -55,68 +57,73 @@ runs:
         echo "::set-output name=git_am_failed::$git_am_failed"
 
         if [ $git_am_failed != 0 ]; then
-          echo "::error::git am failed, most likely due to a merge conflict." && exit 1
+          echo "::error::git am failed, most likely due to a merge conflict."
+          echo "::set-output name=error_occurred::1"
+          exit 1
         else
           # push changes to origin
           git push --force --set-upstream origin HEAD:$temp_branch
         fi
 
-#    - name: Prepare pull request
-#      shell: bash
-#      if: success() && steps.pushbackport.outputs.should_open_pull_request != 0
-#      run: |
-#        # create PR title and description
-#        cat << 'EOF' > pr_body.txt
-#        [${{ steps.targetbranch.outputs.branchname }}] ${{ github.event.issue.title }}
-#
-#        Backport of #${{ github.event.issue.number }} to ${{ steps.targetbranch.outputs.branchname }}
-#
-#        EOF
-#        
-#        # figure out who to tag on the PR
-#        cc_users="@${{ github.event.comment.user.login }}"
-#        
-#        # append PR author if different from user who issued the backport command
-#        if [[ "${{ github.event.comment.user.login }}" != "${{ github.event.issue.user.login }}" ]]; then
-#          cc_users="$cc_users @${{ github.event.issue.user.login }}"
-#        fi
-#
-#        echo "/cc $cc_users" >> pr_body.txt
-#
-#    - name: Open pull request
-#      shell: bash
-#      if: success() && steps.pushbackport.outputs.should_open_pull_request != 0
-#      env:
-#        GITHUB_TOKEN: ${{ inputs.auth_token }}
-#      run: hub pull-request --base ${{ steps.targetbranch.outputs.branchname }} --file pr_body.txt
-#
-#    - name: Prepare error comment for git am failure
-#      shell: bash
-#      if: failure() && steps.pushbackport.outputs.git_am_failed == 1
-#      run: |
-#        cat << 'EOF' > comment_body.txt
-#        @${{ github.event.comment.user.login }} backporting to ${{ steps.targetbranch.outputs.branchname }} failed, the patch most likely resulted in conflicts:
-#
-#        ```shell
-#        EOF
-#        cat git_am_output.txt >> comment_body.txt
-#        cat << 'EOF' >> comment_body.txt
-#        ```
-#
-#        Please backport manually!
-#        EOF
-#
-#    - name: Prepare error comment for unknown failure
-#      shell: bash
-#      if: failure() && steps.pushbackport.outputs.git_am_failed != 1
-#      run: |
-#        cat << 'EOF' > comment_body.txt
-#        @${{ github.event.comment.user.login }} an error occurred while backporting to ${{ steps.targetbranch.outputs.branchname }}, please check the run log for details and backport manually!
-#        EOF
-#
-#    - name: Post error comment to pull request
-#      shell: bash
-#      if: failure()
-#      env:
-#        GITHUB_TOKEN: ${{ inputs.auth_token }}
-#      run: hub api repos/$GITHUB_REPOSITORY/issues/${{ github.event.issue.number }}/comments -F body=@comment_body.txt
+    # Prepare pull request
+    - shell: bash
+      run: |
+        if [[ "${{ steps.pushbackport.outputs.error_occurred }}" != "" || "${{ steps.pushbackport.outputs.should_open_pull_request }}" == "0" ]]; then exit 0; fi
+
+        # create PR title and description
+        cat << 'EOF' > pr_body.txt
+        [${{ steps.targetbranch.outputs.branchname }}] ${{ github.event.issue.title }}
+
+        Backport of #${{ github.event.issue.number }} to ${{ steps.targetbranch.outputs.branchname }}
+
+        EOF
+        
+        # figure out who to tag on the PR
+        cc_users="@${{ github.event.comment.user.login }}"
+        
+        # append PR author if different from user who issued the backport command
+        if [[ "${{ github.event.comment.user.login }}" != "${{ github.event.issue.user.login }}" ]]; then
+          cc_users="$cc_users @${{ github.event.issue.user.login }}"
+        fi
+
+        echo "/cc $cc_users" >> pr_body.txt
+
+    # Open pull request
+    - shell: bash
+      env:
+        GITHUB_TOKEN: ${{ inputs.auth_token }}
+      run: |
+        if [[ "${{ steps.pushbackport.outputs.error_occurred }}" != "" || "${{ steps.pushbackport.outputs.should_open_pull_request }}" == "0" ]]; then exit 0; fi
+        hub pull-request --base ${{ steps.targetbranch.outputs.branchname }} --file pr_body.txt
+
+    # Prepare error comment for git am failure
+    - shell: bash
+      run: |
+        if [[ "${{ steps.pushbackport.outputs.error_occurred }}" == "" || "${{ steps.pushbackport.outputs.git_am_failed }}" == "0" ]]; then exit 0; fi
+        cat << 'EOF' > comment_body.txt
+        @${{ github.event.comment.user.login }} backporting to ${{ steps.targetbranch.outputs.branchname }} failed, the patch most likely resulted in conflicts:
+
+        ```shell
+        EOF
+        cat git_am_output.txt >> comment_body.txt
+        cat << 'EOF' >> comment_body.txt
+        ```
+
+        Please backport manually!
+        EOF
+
+    # Prepare error comment for unknown failure
+    - shell: bash
+      run: |
+        if [[ "${{ steps.pushbackport.outputs.error_occurred }}" == "" || "${{ steps.pushbackport.outputs.git_am_failed }}" == "1" ]]; then exit 0; fi
+        cat << 'EOF' > comment_body.txt
+        @${{ github.event.comment.user.login }} an error occurred while backporting to ${{ steps.targetbranch.outputs.branchname }}, please check the run log for details and backport manually!
+        EOF
+
+    # Post error comment to pull request
+    - shell: bash
+      env:
+        GITHUB_TOKEN: ${{ inputs.auth_token }}
+      run: |
+        if [[ "${{ steps.pushbackport.outputs.error_occurred }}" == "" ]]; then exit 0; fi
+        hub api repos/$GITHUB_REPOSITORY/issues/${{ github.event.issue.number }}/comments -F body=@comment_body.txt
